name: Deploy Astro to Cloud Server

on:
  push:
    branches:
      - main  # 监控 main 分支的推送事件

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: 设置 Node.js 环境
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: ${{ steps.detect-package-manager.outputs.manager }}
          cache-dependency-path: ${{ env.BUILD_PATH }}/${{ steps.detect-package-manager.outputs.lockfile }}

      # Step 3: 安装 pnpm
      - name: Install pnpm
        run: npm install -g pnpm

      # Step 4: 安装依赖并构建
      - name: Install dependencies and build
        run: |
          pnpm install       # 安装依赖
          pnpm run build     # 构建 Astro 项目

      # Step 5: 推送到 GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.6.4
        with:
          token: ${{ secrets.TOKEN }}
          repository-name: njuvtk/njuvtk.github.io
          branch: main
          folder: dist/
          commit-message: "${{ github.event.head_commit.message }} Updated By Github Actions"

      # Step 6: 将静态文件ftp上传
      - name: Upload static files to FTP server
        uses: SamKirkland/FTP-Deploy-Action@4.3.1
        with:
          server: ${{ secrets.IP }}  # FTP 服务器地址
          username: ${{ secrets.UN }}  # FTP 用户名
          password: ${{ secrets.PW }}  # FTP 密码
          local-dir: dist/  # 本地静态文件目录
          remote-dir: /  # 远程服务器目录